PaloAltoNetworks/minemeld-core

minemeld/ft/syslog.py
Fix for PaloAltoNetworks\minemeld-core#35
=> Fix for #35

minemeld/ft/base.py
fix for PaloAltoNetworks/minemeld-core#37
=> fix for PaloAltoNetworks/minemeld-core#37

minemeld/ft/threatq.py
=> Added ThreatQ Miner

minemeld/flask/taxiicollmgmt.py, minemeld/flask/taxiidiscovery.py, minemeld/flask/taxiipoll.py
Fixes PaloAltoNetworks/minemeld-core#45 and improves on PaloAltoNetworks/minemeld-core#42
=> Fixes for #45

requirements.txt
=> Fixes stix/cybox dep issue

minemeld/flask/prototypeapi.py
New prototypes are added to the minemeldlocal.yml library. The library PATH can be set via MINEMELD_LOCAL_PROTOTYPE_PATH config or env variable. If not set the API will take the first directory inside PROTOTYPE_ENV containing the string '/local/', mostly for compatibility.
=> Fixes PaloAltoNetworks/minemeld-core#48

minemeld/ft/taxii.py, tests/test_ft_taxii.py
Completely removed ranges for PaloAltoNetworks/minemeld-core#51
=> Improved #51

minemeld/ft/autofocus.py
Exposed hostname and verify_cert as config vars in AF Miner
=> Exposed hostname and verify_cert as config vars

minemeld/ft/base.py, minemeld/ft/basepoller.py
With this patch checkpoints can be used to save state on disk. The checkpoint file format changes to a pure JSON file, where *state* attribute contains the state of the node at stop.
Subclasses of base can add attributes to the state attribute by overriding the _saved_state_restore and _saved_state_create methods.
Basepoller has been modified to use state to persist the time of the last run and the time of the last successful run. This to speed up restart.
=> Added persistent state in base node

minemeld/ft/taxii.py
=> Fixed error in TAXII Miner and IPv6 observables

minemeld/flask/configapi.py
=> Added validation on the append API

minemeld/comm/amqp.py
- libev waiters for RPC server connections are now set to MAXPRI to improve response to RPC commands even when nodes are busy
=> Improved response times to RPC commands

minemeld/ft/test.py
=> Added Testminer and Testfeed classes for perf testing

minemeld/ft/basepoller.py
Add more details about the status of a node inside the status reports of basepoller.
- added a new field in the status report of the basepoller called sub_state_message
- sub_state setter now accepts a tuple or a string, if a tuple the second element of the tuple is used as sub_state_message. Otherwise sub_state_message is set to *None* and not reported.
minemeld.ft.basepoller class now has a sub_state_message field in its status report containing more details about the sub_state.
=> Added sub_state_message

minemeld/ft/vt.py
Mining VT Intelligence Hunting notifications.
Added a new Miner class based on json.SimpleJSON for mining VT Hunting notifications.
Miner added :-)
=> Added VT notifications miner

docs/schema-indicator-0-1.json
Schema modifications for supporting file hashes and fully support TLP.
- added sha1, sha256, md5 and ssdeep as indicator types
- added *white* as supported share_level
Schema updated.
=> Schema modifications

minemeld/flask/taxiipoll.py
=> Fixes error in poll response headers

minemeld/chassis.py, minemeld/comm/amqp.py, minemeld/ft/test.py, minemeld/mgmtbus.py, minemeld/run/launcher.py
Improvements in the logic of the engine.
- in Chassis, channels for status and logs are now managed by an actor. A dedicated greenlet receiving messages from other glets via a queue. Improves performance and avoid contention between glets.
- in mgmtbus Master init_graph when status operation times out an exception is raised. This to catch errors during the initialisation phase inside the chassis. Before a *reset* message was sent resulting in an empty chassis running.
- in launcher signals are hooked as soon as the processes are spawned.
Faster, stronger
=> Stability improvements

minemeld/ft/phishme.py
Supporting PhishMe Intelligence feed.
- added new Miner class minemeld.ft.phishme.Intelligence based on basepoller
Support for PhishMe Intelligence
=> Added Miner for PhishMe Intelligence

.travis.yml, dependency-links.txt, requirements.txt, setup.py
=> Removed dep links and cifsdk from pypi

minemeld/ft/autofocus.py, minemeld/ft/proofpoint.py, minemeld/ft/recordedfuture.py, minemeld/ft/threatq.py
Fixed behaviours inside Miners where exceptions are not raised if credentials are not set.
=> _build_iterator should raise an error when credentials are not there

minemeld/flask/__init__.py, minemeld/flask/config.py, minemeld/flask/session.py, minemeld/ft/basepoller.py, tests/test_ft_basepoller.py
=> Fixes/Implements #90 and reorgs the flask init code

minemeld/ft/ciscoise.py
=> Fixes error in exception name

minemeld/flask/prototypeapi.py
PaloAltoNetworks/minemeld-node-prototypes#30
=> Adds support for new prototype metadata

minemeld/ft/o365.py
O365 products can change in the XML provided by Microsoft with the list of IPs and URLs. If a user just wants to collect all IPs and URLs related to O365 we could just loop over all the available products in the file.
- if *products* is an empty list all the products inside MS XML file are analyzed
- indicators coming from multiple products are aggregated and *sources* list the names of all the O365 products
- name of products are "lowered"
A new way of collecting O365 IPs and URLs is provided, covering all the possible products
=> Adds support for any O365 product

minemeld/ft/o365.py
To have a single indicator and single update if the same indicator appears in multiple products
=> Add pre-aggregation in O365

minemeld/flask/taxiipoll.py, minemeld/ft/taxii.py, requirements.txt
Adds lz4 compression to indicators stored in Redis to cut memory usage.
=> Lz4 for taxii

minemeld/traced/purge.py
=> Adds config file support in purge utility

minemeld/flask/__init__.py, minemeld/flask/status.py, minemeld/traced/queryprocessor.py, requirements.txt
=> stability improvements for redis interaction

minemeld/comm/amqp.py, minemeld/run/config.py, minemeld/run/launcher.py
=> Improvements in minemeld.run.launcher and run.config

minemeld/ft/basepoller.py, minemeld/ft/dag.py, minemeld/ft/ipop.py, minemeld/ft/op.py, minemeld/ft/syslog.py, minemeld/ft/table.py
=> Adds periodic compaction to minemeld.ft.table.Table

minemeld/flask/configapi.py, minemeld/ft/__init__.py, minemeld/ft/anomali.py, minemeld/ft/autofocus.py, minemeld/ft/base.py, minemeld/ft/basepoller.py, minemeld/ft/cif.py, minemeld/ft/ciscoise.py, minemeld/ft/dag.py, minemeld/ft/google.py, minemeld/ft/ipop.py, minemeld/ft/local.py, minemeld/ft/op.py, minemeld/ft/phishme.py, minemeld/ft/proofpoint.py, minemeld/ft/recordedfuture.py, minemeld/ft/redis.py, minemeld/ft/syslog.py, minemeld/ft/taxii.py, minemeld/ft/threatq.py, minemeld/ft/tmt.py, minemeld/ft/vt.py, minemeld/loader.py, minemeld/mgmtbus.py, minemeld/run/config.py, minemeld/run/launcher.py, nodes.json, requirements.txt, setup.py
First PR for #113
- Implements dynamic loading of nodes and prototypes from external extensions
- Adds support for a new *gc* method in nodes to remove state after nodes have been removed 
=> First PR for #113

minemeld/flask/__init__.py, minemeld/flask/aaaapi.py, minemeld/flask/configapi.py, minemeld/flask/feedredis.py, minemeld/flask/loginapi.py, minemeld/flask/main.py, minemeld/flask/metricsapi.py, minemeld/flask/mmrpc.py, minemeld/flask/prototypeapi.py, minemeld/flask/redisclient.py, minemeld/flask/statusapi.py, minemeld/flask/supervisorapi.py, minemeld/flask/supervisorclient.py, minemeld/flask/taxiicollmgmt.py, minemeld/flask/taxiidiscovery.py, minemeld/flask/taxiipoll.py, minemeld/flask/taxiiutils.py, minemeld/flask/tracedapi.py, minemeld/flask/validateapi.py, minemeld/loader.py, minemeld/run/config.py, tests/test_flask_aaa.py
Side-effect: refactor of flask code to support blueprints and factory pattern
=> Adds support for loading external extensions in API

minemeld/flask/prototypeapi.py, minemeld/run/launcher.py
PROTOTYPE_ENV is now loaded via config in API, adds additional check in launcher
=> Minor fixes for new beta

minemeld/flask/__init__.py, requirements-web.txt
Upgrades to Flask 0.11 and fixes logic in loading external API extensions
Again for #113 
=> Fixes for API external extension

minemeld/chassis.py, minemeld/comm/amqp.py, minemeld/fabric.py, minemeld/ft/base.py
=> Fabric now starts dispatching after all nodes are started

minemeld/flask/session.py
=> Adds session expiration env

minemeld/chassis.py, minemeld/collectd.py, minemeld/flask/configapi.py, minemeld/flask/metricsapi.py, minemeld/flask/statusapi.py, minemeld/ft/basepoller.py, minemeld/ft/table.py, minemeld/mgmtbus.py, minemeld/run/config.py, minemeld/run/launcher.py, tests/test_run_config.py, tests/testproto.yml
=> Polished some code

minemeld/supervisord/listener.py, setup.py
=> Adds supervisord event listener

minemeld/supervisord/listener.py
=> Working commit of listener

minemeld/flask/__init__.py, minemeld/flask/logsapi.py, minemeld/flask/prototypeapi.py, minemeld/flask/supervisorapi.py
Adds API to download logs, manual restart of the engine and fixes a couple of minor bugs
=> Enhancements for supportability

minemeld/flask/__init__.py
=> Fixes bug on validate API

minemeld/mgmtbus.py, minemeld/run/console.py
=> Updates to console

minemeld/ft/base.py, minemeld/ft/basepoller.py, minemeld/mgmtbus.py, minemeld/run/console.py, tests/test_ft_basepoller.py
- Adds support for indicators of different types inside basepoller
- Adds support for new signal message to nodes, and for flush signal in basepoller
=> Improvements for basepoller

minemeld/flask/configapi.py, minemeld/run/console.py
=> Fixes #137 and adds handling of missing running config scenario

docs/schema-indicator-0-1.json
=> Adds new indicator types

minemeld/flask/statusapi.py, minemeld/ft/base.py, minemeld/ft/basepoller.py, minemeld/ft/local.py
=> Improves signal message and expose signal via API

minemeld/ft/actorbase.py, minemeld/ft/base.py, minemeld/ft/ipop.py, minemeld/ft/op.py, tests/test_ft_ipop.py, tests/test_ft_op.py
=> aggregators now check type of withdrawn indicators if present

minemeld/flask/feedredis.py, minemeld/flask/redisclient.py, minemeld/flask/session.py
=> Adds a maximum to the number of connections to redis for authentication

minemeld/ft/syslog.py
Moved to actor based model inside Syslog Miner and fixed some bugs along the way.
=> Fixes for syslog miner

minemeld/ft/table.py
=> Fix compact loop taking too much time

minemeld/flask/extensionsapi.py
=> Fixes error on extension uninstall

minemeld/flask/statusapi.py
- new API endpoint for starting a job to backup local MM directory (config, prototype, library)
- new API endpoint to download the result of the job
=> Adds backup API

minemeld/ft/basepoller.py, tests/test_ft_basepoller.py
=> Adds optional pre aggregation in basepoller

minemeld/traced/writer.py
=> Decreased trace writer threshold to 70

minemeld/ft/basepoller.py
=> Fix for aggregate table

minemeld/ft/basepoller.py, minemeld/ft/table.py, tests/test_ft_basepoller.py
=> Fixes a bug in table for unicode indicators

minemeld/ft/basepoller.py
=> Fixes aggregation step in basepoller

minemeld/flask/extensionsapi.py, minemeld/flask/prototypeapi.py
=> Adds modules cached invalidation on reload

minemeld/ft/redis.py, minemeld/ft/table.py, minemeld/ft/taxii.py, tests/test_ft_redis.py, tests/test_ft_taxii.py
=> Adds max_entries to feeds and taxii feeds, and hashes support in TAXII

minemeld/ft/base.py, minemeld/packages/gevent_openssl/COPYING, minemeld/packages/gevent_openssl/SSL.py, minemeld/packages/gevent_openssl/__init__.py, minemeld/run/launcher.py
=> Adds monkey patching of pyOpenSSL

minemeld/flask/extensionsapi.py
=> Adds config parameter to control the API for installing new extensions

minemeld/flask/feedredis.py
=> Implements #162

minemeld/ft/azure.py, minemeld/ft/o365.py, minemeld/packages/gevent_openssl/SSL.py
=> Fixes #170 & #171

minemeld/ft/taxii.py
Adds incremental query, fixes some logic
=> Improvements to the TAXII Miner

minemeld/ft/mm.py, minemeld/ft/taxii.py, nodes.json
=> Adds MineMeld feed miner

minemeld/ft/json.py
=> Adds basic auth support to JSON miner

minemeld/run/console.py
mm-console now generates JSON instead of pretty printed python, better interop
=> JSON output for mm-console

minemeld/ft/taxii.py
Adds support for LinkObjectType and adds a new flag to ignore composition operator
=> Improvements for TAXII Miner

minemeld/ft/auscert.py
- redirect returned from login is not followed
- a check is performed if the login was successful. Check is based on the return cookie
- a check is performed on the page returned by the feed URL
=> Adds improvements to AusCERT feed sources

docs/schema-indicator-0-1.json, minemeld/ft/taxii.py, tests/test_ft_taxii.py
Adds support for FileObjectType and SocketAddressObjectType
=> Improvements to STIX Miner

minemeld/ft/taxii.py
=> Fixed bug in TAXII Miner

minemeld/ft/taxii.py
=> Adds support for Status Messages in TAXII Client

minemeld/ft/mm.py
=> Implements enhancement #193

minemeld/ft/csv.py
=> Adds support for Basic Auth to CSV Miner

minemeld/ft/csv.py
=> Fix for CSV Basic Auth

minemeld/flask/extensionsapi.py
=> Fixes #202 adding check for freeze.txt

AUTHORS, minemeld/ft/table.py, minemeld/ft/taxii.py, minemeld/ft/utils.py
Added in extra observable types to be parsed from a taxii feed.
=> Updates to taxii observables

.gitignore, AUTHORS, minemeld/ft/phishme.py
=> Changes to add custom user agent string to PhishMe Intelligence miner

minemeld/ft/taxii.py
=> Bug fix for when a file_name is already a str

minemeld/ft/basepoller.py, tests/test_ft_basepoller.py
=> Adds support for handling partial results in base poller aggregation

AUTHORS, minemeld/ft/json.py
Add the abiltity to use headers in the json-miner.
=> Header extension for Json-Miner #216

minemeld/ft/basepoller.py, tests/test_ft_basepoller.py
=> Fixes first_seen base in basepoller

tests/test_ft_basepoller.py
=> Adds an additional test to first seen

minemeld/flask/feedredis.py
Improves flexibility of CSV support in minemeld.flask.feedredis. Parameters:
- _h_ generates a CSV header. Default _true_
- _f_ adds a field from the specified indicator attribute. Multiple _f_ parameters can be specified. If the value of the _f_ is _indicator_, the indicator itself will be added. The name of the column for that specific parameter can be specified by appending a _|_ at the end of the _f_ parameter value and then specify the column name
- _ubom_ adds UTF-8 BOM at the beginning of the file. This is for compatibility. Default _false_
- _tr_ is supported
Example:
```
https://\<minemeld\>/feeds/feedName?v=csv&tr=1&f=confidence&f=sources|feeds&f=indicator|clientip&f=dshield_email
```
Result:
```
confidence,feeds,clientip,dshield_email …
```
=> CSV output - flexibility improvements

minemeld/flask/aaa.py, minemeld/flask/aaaapi.py, minemeld/flask/config.py, minemeld/flask/jobs.py, minemeld/flask/statusapi.py, minemeld/flask/utils.py, minemeld/run/restore.py, setup.py
=> Implements backup restore feature

minemeld/ft/op.py
Fixes #229 by adding a new config option to the aggregator node to ignore cases.
=> Adds ignore_cases option

minemeld/ft/basepoller.py, minemeld/ft/recordedfuture.py
=> Fixed entity URLs in recordedfuture

minemeld/ft/basepoller.py, minemeld/ft/o365.py
=> Fixes problem with flush and makes the base URL of o365 configurable

minemeld/flask/configdataapi.py
=> Improved localdb schema

minemeld/flask/__init__.py, minemeld/flask/sns.py, minemeld/flask/statusapi.py
Implements the basic Simple Notification Service to enable the "Make a Wish" web-ui feature.
=> Basic Simple Notification Service

minemeld/ft/http.py
=> Adds basic auth support on plain text miner

minemeld/flask/configdataapi.py
=> Fixes problem with localdb API

minemeld/flask/feedredis.py
Solved a issue with a single IPv4 indicator crashing the CarbonBlack formatter
=> Fixes single IPv4 indicator issue in CarbonBlack formatter

minemeld/ft/taxii.py
With the current implementation of the TAXII Miner, the Miner at each polling interval requests indicators with timestamp falling into the time window starting with the last polling time. This could be an issue when the Miner and the server clocks are out of sync.
This PR uses the timestamp associated to the STIX packages received from the TAXII server as reference.
=> Improves polling sync with TAXII Server

minemeld/ft/taxii.py
=> Adds support for information source identity

minemeld/ft/json.py, minemeld/ft/visa.py, nodes.json
This PR implements the Visa TI API Miner. It is a JSON based API demanding Client Certificate support. This PR includes modifications in `json.py` (SimpleJSON class) to implement support for Client Certificates at its level.
=> Visa Threat Intelligence API Miner

minemeld/ft/dag.py
fixes cases where self.statistics['ignored'] not incremented and log
all ignored cases.
=> Update minemeld.ft.dag.DagPusher() to support IPv6 indicators.  Also

minemeld/ft/o365.py, nodes.json
See PaloAltoNetworks/minemeld-core#267
=> O365 API Miner

minemeld/loader.py
=> Adds support for pip 10.0

minemeld/extensions/manager.py
=> Adds support for pip > 10.0

minemeld/extensions/manager.py, minemeld/loader.py
Thanks @satosi-k and @TiagoSantos84
=> Fixes support for pip > 10.0.0

minemeld/ft/taxii.py
=> Adds check for unicode in properties decoding. Fix #275

minemeld/ft/taxii.py
=> Added comptability method to replace old set_id_namespace

minemeld/ft/taxii.py
=> Fixed age out logic of Taxii DataFeed

minemeld/ft/taxii.py
=> Adds suppot for Email Addresses in TAXII DataFeed

minemeld/ft/o365.py
=> Supports changes to O365 API

minemeld/ft/o365.py
=> Fix oversight

minemeld/ft/ipop.py, minemeld/ft/st.py, tests/test_ft_ipop.py
- Fixes #296
- Adds test to reproduce bug conditions
=> Fixes #296

requirements-web.txt, requirements.txt
=> Updated deps for security issues

minemeld/ft/o365.py
=> Adds support for disabiling integrations

minemeld/ft/dag.py
- Add warning log when ip has no tags.  Should not happen.
- Add XXX comment for "unknown" tag case.  We may want to remove this.
- Best practice is to always use format specifier for logger,
for example:
-        LOG.debug(ctags)
+        LOG.debug('%s', ctags)
- Add XXX comment "use constant for chunk size".  Revisit size when
get deeper into resync.
- Add some helpful debugs.
- Change from debug to warning on unknown indicator.  Should really
not happen so let's log it always.
- Eliminate bare excepts to either use the expected exception
(OSError) or Exception for broader exceptions.
- Fix missing format argument on LOG.exception().
=> Changes resulting from code review.  No functional changes except for logging.

minemeld/ft/dag_ng.py, nodes.json
require PAN-OS 8.0 and greater.  New node is based on dag.py.  This
first step validates each device is running PAN-OS 8.0 or greater; if
not an error is logged API requests to the device are not performed.
=> Create new prototypes and node for dagPusher enhancements which will

minemeld/ft/dag_ng.py
objects using PAN-OS 8.0 show object "start-point" and "limit"
arguments.
Performance enhancement to get all registered-ip objects vs. get by
tag prefix+watermark, then get each IP to obtain all tags.
Fix bug where IP objects from firewall were not canonized with host
prefix for matching in indicator table.
=> Enhance _get_all_registered_ips() to work with >500 registered-ip

minemeld/ft/dag_ng.py
minutes.  On PAN-OS 9.0 and greater also set the tag timeout.
If canary is not found, restart the device pusher so it will
resync.
=> Add a non persistent canary registered-ip and check it every 5

minemeld/ft/dag_ng.py
for up to 1 second or 512 messages, and batch them in a single user-id
update API request.
=> Performance enhancement: read device queue messages of the same type

minemeld/ft/dag_ng.py
The tag name cannot contain the following:
- single quote
- double quote
- greater than one consecutive space
And cannot be the case insensitive words:
- and, or, not
=> Update tag name munging to reflect known invalid characters and words.

minemeld/ft/basepoller.py
=> Handle indicator update when previous indicator is updated by removing

minemeld/ft/basepoller.py
=> Fixes #342

minemeld/ft/azure.py
To improve the ability of filtering Azure endpoints, now the indicators are pre-aggregated before the updates. New attributes ending with `_list` are generated with all the values of each specific Azure attribute. Example:
```
{
"_age_out": 4294967295000,
"confidence": 100,
"azure_system_service_list": [
"azuread",
"azureidentity"
],
"last_seen": 1566561612635,
"azure_platform_list": [
"azure"
],
"azure_region": "",
"azure_name": "AzureActiveDirectoryDomainServices",
"share_level": "green",
"_last_run": 1566561900676,
"sources": [
"cloudIPsWithServiceTags"
],
"azure_name_list": [
"azureactivedirectory",
"azureactivedirectorydomainservices"
],
"azure_id_list": [
"azureactivedirectory",
"azureactivedirectorydomainservices"
],
"azure_region_list": [
""
],
"azure_system_service": …
```
=> Improvs Azure Miner by pre-aggregating the indicators

minemeld/flask/feedredis.py
Switch feed messages from JSON/Text to HTML to improve compatibility with older PAN-OS releases
=> Feed errors from JSON/Text to HTML

minemeld/ft/recordedfuture.py, nodes.json
Same as #353 but rebased on the most recent code.
Luigi
=> New Recorded Future Miner

minemeld/ft/basepoller.py
=> Fixes diff logic

minemeld/ft/ipop.py
Added a new option to merge list attributes by extending them.
Signed-off-by: Luigi Mori <l@isidora.org>
=> Adds new option list merge to IPv4 Aggregator

minemeld/ft/azure.py
=> Adds support for cloud config in Azure JSON

minemeld/ft/bambenek.py, minemeld/ft/csv.py, nodes.json
=> Adds support for new Bambenek feeds

.circleci/config.yml, minemeld/ft/taxii2.py, requirements-dev.txt
- pinned version of virtualenv
- added support for confidence in STIX2.1 Miner
=> Small improvement to STIX2 Miner and build environment

minemeld/ft/cofense.py, nodes.json
Adds support for Cofense Triage API
=> Adds support for Cofense Triage API

minemeld/flask/taxiipoll.py, minemeld/ft/taxii.py, requirements.txt
=> bumps lz4 version

minemeld/ft/recordedfuture.py
@christian-recordedfuture there were some conflicts with `develop` branch in #377, I created a new PR to resolve those. Could you check?
Thanks,
Luigi
=> New PR #377

minemeld/flask/feedredis.py
=> Improved scalability of summarization option

requirements-web.txt, requirements.txt
Bumping deps to avoid false alarms in static security scanners.
=> Bumped deps
