minemeld/ft/taxii.py, tests/test_ft_basepoller.py, tests/test_ft_local.py, tests/test_ft_taxii.py, tox.ini
Fixed PaloAltoNetworks/minemeld-core#50 and PaloAltoNetworks/minemeld-core#51
Fixed some tests mock.patch after utc_millisec has been swicthed to time.time
=> Fixes for #50 and #51

minemeld/flask/__init__.py, minemeld/flask/aaa.py, minemeld/flask/configapi.py, minemeld/flask/login.py, minemeld/flask/session.py
Authentication performed via login API in login.py checks credentials against htpasswd DB
and return a session cookie.
Session cookie is managed via flask session interface in session.py. Sessions are stored
on Redis with fixed expiration.
Added 2 new API /login and /logout
=> Added session based authorization to API.

minemeld/ft/taxii.py, tests/test_ft_taxii.py, tests/test_ft_taxii_stix_package_1.xml
This change adds support for STIX Observable Composition. Limitations:
- only OR composition
- only 1 level of composition (no compositions of compositions of ...)
- observables inside composition should be referenced.
Added quick and dirty test for it.
=> STIX observable compositions

minemeld/comm/amqp.py
Instead of localhost. Avoid issues with gevent problems in parsing /etc/hosts file
=> Forced AMQP default to 127.0.0.1

minemeld/flask/__init__.py, minemeld/flask/configapi.py, minemeld/flask/session.py, minemeld/ft/logstash.py, minemeld/ft/redis.py, minemeld/ft/taxii.py, minemeld/traced/queryprocessor.py
- removes references to localhost, using 127.0.0.1 instead to avoid DNS issues
- redis connection settings are now passed to the session init function instead of using the defaults
- configapi now loads config before first request
=> Removes localhost, clean up session interface and adds init to config

minemeld/chassis.py, minemeld/comm/amqp.py, minemeld/flask/__init__.py, minemeld/flask/status.py, minemeld/ft/base.py, minemeld/ft/basepoller.py, minemeld/mgmtbus.py, minemeld/run/launcher.py
- nodes can send to state to mgmtbus master
- mgmtbus master collects state notifications and builds graph state
- mgmtbus master forwards state notifications to Redis publish
- added API to receive status notifications from Redis
- added timeout in status/minemeld API to cope with engine restart
- added renice of chassis processes
- fixed a startup logic issue
=> Added status streaming functionalities to node (and other tweaks)

.travis.yml, dependency-links.txt, minemeld/ft/cif.py, requirements.txt, setup.py
A new Miner has been added for CIF TI framework.
- a new Miner class has been added, minemeld.ft.cif.Feed. A subclass of basepoller
- the Miner is based on cif-sdk-py python package not available via pip, dependency
links have been used to download the tagged release from github.
- modified platter script to use the appropriate building flags for dependencies
- upgraded to ujson 1.34, required by cif-sdk-py
A new Miner is available for the CIF framework.
=> New CIF Miner

minemeld/ft/cif.py
- increases timeout on CIF Client, for large queries
- if token, remote or filters are not set RuntimeError is raised to not set the last_successful_run value
=> Increased timeout in CIF and fixed logic bug

minemeld/comm/amqp.py
RPC requests handled by AMQPRpcServerChannel should be served with high priority.
AMQPRpcServerChannel currently spawns a new greenlet per request, the greenlet then is executed by gevent with other callbacks. AMQPRpcServerChannel instead should directly serve the call to not lose the priority.
- consume now directly calls _callback instead of _g_callback
- removed _g_callback
AMQPRpcServerChannel will serve RPC requests directlty inside the event handling greenlet.
=> RPC requests are served immediately

minemeld/ft/basepoller.py, minemeld/ft/local.py, minemeld/ft/phishme.py, minemeld/ft/utils.py, tests/test_ft_autofocus.py, tests/test_ft_basepoller.py, tests/test_ft_local.py, tests/test_ft_redis.py, tests/test_ft_taxii.py
minemeld.ft.basepoller.BasePoller class is too complex, the logic is unclear and difficult to maintain.
- the class has been modified to have 3 different greenlets: an actor glet, a poll glet and an age out glet.
- the actor glet waits on a queue for commands: *poll*, *age_out*, *sudden_death*, *garbage_collect*. Each command has a timestamp, if the timestamp is less than the ending time of the previous execution of the same command the command is ignored.
- the age_out glet just periodically sends *age_out* commands to the actor glet queue
- the poll glet periodically send a sequence of *poll*, *suddend_death*, *age_out* and *garbage_collect* in the queue
The logic now should be simpler to understand.
=> Change minemeld.ft.baspoller.BasePoller structure

minemeld/flask/__init__.py, minemeld/flask/aaa.py, minemeld/flask/aaaapi.py, minemeld/flask/config.py, minemeld/flask/configapi.py, minemeld/flask/feedredis.py, minemeld/flask/metricsapi.py, minemeld/flask/taxiipoll.py, minemeld/flask/utils.py
Users have requested a UI for managing WebUI Admins and for managing credentials for feeds access. 
- MineMeld API process now reads the configuration from a directory: all the files inside the directory with pattern <number>-*.yml are read in order, merged and treated as config. The config directory is the contents of the environment variable MM_CONFIG + *api*, for compatibility with old releases.
- The config directory can also contain one or more Apache HTPASSWD files where admin/feeds access credentials are stored hashed and salted.
- MineMeld API monitors the directory for changes, if a yml or htpasswd file is added, deleted or modified the config is automatically  reloaded. This happens by polling the directory every second and checking the mtime of the files.
- MineMeld API …
=> Implements AAA API and improves API config management

minemeld/flask/__init__.py, minemeld/flask/aaa.py, minemeld/flask/aaaapi.py, minemeld/flask/config.py, minemeld/flask/feedredis.py, minemeld/flask/taxiicollmgmt.py, minemeld/flask/taxiidiscovery.py, tests/feeds.htpasswd, tests/test_flask_aaa.py, tests/wsgi.htpasswd, tox.ini
Various improvements on MineMeld AAA.
- Authorizations for TAXII collection management and discovery service are now dynamically calculated based on the tags of the existing TAXII Feeds
- by default config lock file is now created under /var/run/minemeld. Since /var/run should be on a tmpfs volume this prevents issue if minemeld instance is not properly shut down. Path can be controlled via *API_CONFIG_LOCK* environment variable
- added unittests for API AAA logic
- fixed an initialization issue in flask
- fixed PEP8 (@kevinsteves). Max line length is now set to 100.
AAA should be more stable and powerful.
=> Improvements on #90

minemeld/ft/ciscoise.py, minemeld/ft/dag.py, minemeld/packages/ise/__init__.py, minemeld/packages/ise/ers.py
Add experimental miner for IP to SGT (Security Group Tag) mappings
from Cisco Identity Services Engine (ISE) using ERS (External RESTful
Services) API.
Adds ciscoise.yml with 2 prototypes:
ers_sgt: miner using class minemeld.ft.ciscoise.ErsSgt.  Config
variables are:
hostname: ISE hostname
username: ERS API username (in ISE admin group ERS Operator)
password: ERS API password
verify_cert: HTTP Requests verify cert
timeout: HTTP Requests timeout
NOTE: These can be specified in the prototype config or a side config.
prefix: SGT prefix (default ise_sgt)
sgt_dag: output node using class minemeld.ft.dag.DagPusher to push
IP to SGT mappings to PAN-OS devices via DAG (registered-ip).
minemeld.ft.dag.DagPusher has been modified to handle attributes of
type list for one to many IP to SGT cases. …
=> Add Cisco ISE IP to SGT miner

minemeld/ft/dag.py
Fix from @kevinsteves to remove *persistent* attribute from DAG *unregister* messages.
=> Fix for DagPusher

minemeld/ft/dag.py
Allow api_key vs. api_username/api_password in device list.
=> Allow pan.xapi.PanXapi() api_key in device list.

minemeld/ft/table.py, tests/test_ft_autofocus.py, tests/test_ft_basepoller.py, tests/test_ft_dag.py, tests/test_ft_ipop.py, tests/test_ft_local.py, tests/test_ft_op.py, tests/test_ft_syslog.py, tests/test_ft_table.py, tests/test_ft_taxii.py
Adds iterator context in table query
Adds code to close table in destructor
Adds counter to track lazily deleted index keys
Side-effect: fixed tests
=> Minor improvements in minemeld.ft.table.Table

minemeld/ft/base.py, minemeld/mgmtbus.py, minemeld/run/launcher.py
- default number of chassis is 2*# of cores
- added argument to specify a # nodes/chassis ratio, to avoid aberrant scenario with 1 node per core
- now status updates use a virtual clock instead of real time for better consistency
=> Multi-chassis improvements

minemeld/chassis.py, minemeld/comm/amqp.py, minemeld/flask/configapi.py, minemeld/flask/mmrpc.py, minemeld/flask/tracedapi.py, minemeld/ft/actorbase.py, minemeld/ft/base.py, minemeld/ft/basepoller.py, minemeld/ft/dag.py, minemeld/ft/ipop.py, minemeld/ft/logstash.py, minemeld/ft/op.py, minemeld/ft/redis.py, minemeld/ft/syslog.py, minemeld/ft/taxii.py, minemeld/ft/utils.py, minemeld/mgmtbus.py, minemeld/run/config.py, minemeld/run/launcher.py, minemeld/startupplanner.py, requirements.txt, tests/test_startupplanner.py
- Configapi now uses mgmtbus to hup Miners
- Introduces actorbase that can be used to serialize message processing inside Nodes
- Each node now can receive a different startup message
- Introduces startup planner, a mechanism to define how each should be initialized at startup
=> Adds throttled updates

minemeld/flask/configapi.py, minemeld/flask/prototypeapi.py, minemeld/flask/utils.py
Users are currently able to create new local prototypes but a feature is missing to remove old, unused ones.
- adds a new API for deleting local prototypes. Before removal a check is made to verify that the prototype to be delete is not used in running or committed config.
A new API is exposed to delete local prototypes. This API will be then used by the WebUI
=> Added delete prototype API

minemeld/supervisord/listener.py
In case of exception OK is still sent back to supervisord
=> small fix for listener

minemeld/ft/base.py, minemeld/ft/basepoller.py, minemeld/ft/redis.py, minemeld/ft/taxii.py, minemeld/run/launcher.py, tests/test_ft_base.py, tests/test_ft_redis.py, tests/test_ft_taxii.py
Improvements:
- if *conditions* is *null* in filters, now it is considered an empty list
- now checkpoints are removed after nodes switch from READY state. If a node fails during configuration saved state is still consistent. Useful for recovering from faulty prototypes or faulty configs
- default number of nodes per chassis has been increased to 15
=> Improvements

minemeld/extensions/__init__.py, minemeld/extensions/manager.py, minemeld/flask/__init__.py, minemeld/flask/extensionsapi.py, minemeld/flask/jobs.py, minemeld/flask/jobsapi.py, minemeld/flask/prototypeapi.py, minemeld/flask/supervisorapi.py, minemeld/loader.py, minemeld/run/freeze.py, setup.py
This PR introduces changes for supporting #113 via API. Using the API users can install extensions from wheel files or git repos, uninstall extensions, activate & deactivate them.
A good number of modifications to achieve the goal:
- added API endpoint to list activated/installed extensions
- added API endpoint to upload extensions wheel files
- added API endpoint to retrieve extensions from git repos
- added API endpoint to retrieve refs from git repos (UI helper)
- added API endpoint to uninstall (i.e. delete) installed extensions
- added API endpoint to activate extensions
- added API endpoint to deactivate extensions
- since activation/deactivation and git ops could be long running, a new frameworks has been introduced to let the API run long running tasks in background (jobs.py)
- …
=> Adds support for external extensions API and jobs API

minemeld/flask/__init__.py, minemeld/flask/aaa.py, minemeld/flask/aaaapi.py, minemeld/flask/config.py, minemeld/flask/configapi.py, minemeld/flask/extensionsapi.py, minemeld/flask/feedredis.py, minemeld/flask/jobs.py, minemeld/flask/jobsapi.py, minemeld/flask/logger.py, minemeld/flask/loginapi.py, minemeld/flask/logsapi.py, minemeld/flask/metricsapi.py, minemeld/flask/mmrpc.py, minemeld/flask/prototypeapi.py, minemeld/flask/redisclient.py, minemeld/flask/session.py, minemeld/flask/statusapi.py, minemeld/flask/supervisorapi.py, minemeld/flask/taxiicollmgmt.py, minemeld/flask/taxiidiscovery.py, minemeld/flask/taxiipoll.py, minemeld/flask/taxiiutils.py, minemeld/flask/tracedapi.py, minemeld/flask/utils.py, minemeld/flask/validateapi.py, tests/test_flask_aaa.py
Support for read_only and read_write admin roles to have better granularity on admin authorizations.
READ_WRITE authorization:
- Added a subclass of flask Blueprint that decorates view funcs with an auth check function and an audit log function
- Each view function of the API is now decorated with *read_write*, *login_required* and *feeds* additional keywords. Default are the strictest: *read_write*: True, *login_required*: True, *feeds*: False.
- Added support for new *READ_WRITE* config parameter. Value should be a comma separated list of user_ids to give read-write access to
- When *READ_WRITE* is set, only users in *READ_WRITE* are able to access routes with *read_write* flag. For everybody else the routes return a 403 error or 401, if a feed use tries to access an API endpoint.
- …
=> Adds read_write role to admins and audit logs

minemeld/flask/statusapi.py, minemeld/flask/supervisorapi.py, minemeld/flask/tracedapi.py, minemeld/run/launcher.py, minemeld/traced/main.py, minemeld/traced/purge.py, minemeld/traced/writer.py
- engine refuses to start if there is less than MM_DISK_SPACE_PER_NODE KB per configure node of available space. Default *MM_DISK_SPACE_PER_NODE* is 10K (= 10MB)
- engine every minute check for available disk space, if disk space falls below threshold an engine stop is triggered
- trace daemon checks every minute for available disk space, if available space falls below a threshold traces are not written
- a new API endpoint is provided to purge all the traces
=> Adds support for disk space checking

docs/schema-indicator-0-1.json
New indicator type introduced for process command lines.
=> Adds process.command-line in schema

minemeld/ft/basepoller.py
Stops logging errors when aggregate-temp does not exist.
=> Minor fix for gc of basepoller

docs/schema-indicator-0-1.json, minemeld/flask/__init__.py, minemeld/flask/configapi.py, minemeld/flask/configdataapi.py, minemeld/ft/taxii.py, requirements.txt
Some TAXII servers requires client cert authentication. This was available on the engine but not exposed on the WebUI. This commit adds support for client cert auth on the WebUI and improves the TAXII Client code.
- adds API to upload certificates and private keys for specific nodes
- improves support for client auth (both cert and credentials) inside TAXIIClient
- adds support for non standard port in TAXIIClient (Fixes #173)
- adds support for subscription_id in TAXIIClient
- adds support for DHS AIS marking in TAXIIClient
Better interoperability with 3rd party TAXII Servers
=> TAXII Client improvements

minemeld/ft/taxii.py
Adds support for missing timestamp in indicator and handles exception for strange formats of IP Addresses.
=> Fixes for STIX parsing inside TAXII Miner

minemeld/extensions/manager.py, minemeld/flask/__init__.py, minemeld/flask/aaa.py, minemeld/flask/prototypeapi.py, minemeld/loader.py, minemeld/run/config.py
Extensions provide a mechanism to extend MineMeld with custom nodes. Currently extension can only provide new nodes, new API endpoints and new prototypes, what is missing is a way to extend WebUI to provide a proper UI for the new nodes. This commit adds support for WebUI extensions.
- added a new entrypoint for WebUI extension. The new entry point points to a flask blueprint serving static files with the UI extension. 
Extensions can now also add new features to the WebUI.
=> Adds support minemeld webui extensions

minemeld/extensions/manager.py, minemeld/flask/__init__.py, minemeld/flask/extensionsapi.py, minemeld/flask/logger.py, minemeld/loader.py
After an API restart, extensions downloaded via git are not shown as "activated". The problem is that the new API process inherits sys.path from the parent gunicorn that is not aware of the newly activated extensions.
A new function is defined in minemeld.extensions to verify that all the paths inside freeze.txt are available in sys.path. This function is called when extensions API are initialized.
=> Fixes bug in activation of extensions downloaded via git

minemeld/ft/taxii.py
Some TAXII feeds provides IOCs as Observables with no encapsulating indicators. With this PR the TAXII Miner will create a fake indicator to wrap observables.
This can be controlled via `create_fake_indicator` boolean flag in config, default is *true*.
=> TAXII Miner - Fake indicator

minemeld/ft/csv.py
Shame on me ! *auth* parameter seems to be ignored when set on session, it should be passed when preparing the request.
=> CSV Basic Auth fix - again

minemeld/flask/prototypeapi.py, minemeld/run/config.py
There are scenarios where extension writers want to override prototypes included in the default library. Example: adapt the prototype config to a specific environment without changing the prototype names.
- in the API and config loader prototype paths from extensions are added to the front of the prototype paths list. The paths list is traversed in order from front to back, and the first matching prototype is used.
Prototypes in extension have higher priority than prototypes in default library.
=> Change priority of prototypes

minemeld/run/cacert_merge.py, minemeld/run/launcher.py, setup.py
Currently MineMeld Miners nodes based on `requests` (that is 99.9% of them) trust the CAs included in the `certifi` library. Adding new certificates to that bundle is a tedious process that should be reapplied after every upgrade. 
With this PR a new utility (written by @kevinsteves) is added to MM to easily generate new certificate bundle from `certifi` and a list of additional certs. The autoupdate utility of MineMeld will use this utility after every upgrade to create a trusted bundle from `certifi` and the cert files in a specific directory. In the MineMeld container the utility is called inside the startup script to support upgrades of existing volumes.
- added a new command line utility in minemeld.run path for managing CA certs bundles
- added a new script entry point in setup.py …
=> Adds utility for managing trusted CA certs

minemeld/ft/base.py, minemeld/ft/basepoller.py, tests/test_ft_base.py
MineMeld engine supports an environment variable called _MM_DISABLE_FULL_TRACE_. When the variable is set only a limited set of traces is generated by a node. During troubleshooting it may be useful to enable to full set of traces.
This commit adds a new signal called trace to each node. When _MM_DISABLE_FULL_TRACE_ is set, if a node receives a trace signal the full set of trace messages is generated for 10 minutes and then automatically disabled.
- added new __disable_full_trace_ attribute to minemeld.ft.base.BaseFT to track full trace status
- __disable_full_trace_ is set to _True_ if _MM_DISABLE_FULL_TRACE_ is set, otherwise is set to _False_
- _mgmtbus_signal_ in BaseFT sets __disable_full_trace_ when trace signal is received
- __disable_full_trace_ is reset after 10 mins via a glet …
=> Adds support for trace signal

minemeld/flask/feedredis.py, requirements.txt
Currently MineMeld does not support generating feeds in CSV format or McAfee Web Gateway format. Support for these 2 formats is useful for interoperating with 3rd party systems, like [Splunk Lookup](http://docs.splunk.com/Documentation/Splunk/6.6.0/Knowledge/ConfigureCSVlookups) tables and [McAfee Web Gateway](https://community.mcafee.com/docs/DOC-5208).
- in minemeld.flask.feedredis module added support for McAfee Web Gateway format (see above). Format is selected by setting the _v_ parameter to _mwg_. Supports _tr_ parameter and _t_ parameter for declaring the list type (see McAfee Web Gateway format link above). If _t_ is set to _ip_, _tr_ is automatically set to _true_. Default value for _t_ is _string_.
Example:
```http://<minemeld>/feeds/<feedname>?v=mwg&t=ip```
- in …
=> Adds support for McAfee Web Gateway format and CSV

minemeld/ft/taxii.py
Some TAXII Servers do not support timestamps with second. precision and throw an error when a poll request is performed with timestamps including seconds.
- a new flag is added to TAXII Miner to support stripping seconds from timestamps. When _ lower_timestamp_precision_ is set to _true_, the begin and end timestamps of the poll requests are stripped of the seconds.
New flag for TAXII Miner to improve compatibility with specific TAXII Servers.
=> Adds lower_timestamp_precision flag to TAXII miner

minemeld/flask/configapi.py, minemeld/run/restore.py
Now the restore utility deletes the existing candidate and restart the API process to trigger a revert.
=> Improved restore utility to revert candidate to running after restore

minemeld/flask/feedredis.py
Added formatter that implements BlueCoat custom URL format as described at [https://www.bluecoat.com/documents/download/a366dc73-d455-4859-b92a-c96bd034cb4c/f849f1e3-a906-4ee8-924e-a2061dfe3cdf](url)
It expects the value 'bc_category' in the indicator. The value can be either a single string or a list of strings.
- In case 'bc_category' is a list then the indicator will be placed in all provided categories
- If 'bc_category' does not exist then the indicator will be placed in the category 'BC_None'
=> Added formatter that implements BlueCoat custom URL format

minemeld/flask/configdataapi.py, minemeld/ft/localdb.py, nodes.json
Current version of *local* Miners have been designed to manage short whitelists/blacklists. To use MineMeld in an incident response chain these Miner should be improved to remove the current limitations:
- no support for expiration per indicator
- limited API
- slow and rudimental backend based on a simple YAML file, limiting performance and scalability
- a new Miner has been introduced to manage a local list of indicators using sqlite as backend
- the config data API has been extended to support sqlite as config data type
- in the backend DB there is a single table called indicators. Each indicator has the following fields:
- indicator - the indicator name
- type - the indicator type
- attributes - a JSON document with the additional attributes
- update_ts - last update time for this …
=> Adds new local miner for local DB

minemeld/flask/metricsapi.py, minemeld/mgmtbus.py
Now metrics are stored are stored with a name derived from MD5 to avoid problems with long names while avoiding collisions.
=> Fix for ATF-3245

minemeld/flask/__init__.py, minemeld/flask/feedredis.py, minemeld/flask/sns.py, minemeld/flask/statusapi.py
Bluecoat formatter needs to iterate all indicators to create a
category-based dictionary. It might take a few seconds.
Adding gevent.sleep(0) in the main loop to avoid starvation.
=> YouTube Miner can generate tens of thousands of URL indicators.

minemeld/flask/feedredis.py
BlueCode formatter includes a potentially long loop. Adding gevent.sleep(0) to avoid starvation.
=> gevent sleep in (possible) long loop in bluecoat formatter

minemeld/flask/sns.py
Constant initialization now waits for the `config.py`package initializations.
Refactored constant names for consistency
=> Moved config load to init_app()

minemeld/ft/taxii.py
Title of DataFeed STIX package can be specified via a list of attributes, first attribute found in the indicator is used.
Example config:
```
attributes_package_title:
- stix_package_title
- autofocus_label
```
=> STIX Package title in DataFeed Output

AUTHORS, minemeld/ft/http.py
Second take on #257 
Signed-off-by: Egon Kidmose egk@es.aau.dk
I accept that the Apache License applies to the included changes.
=> Support for feed in encodings other than UTF-8. Closes #256.

minemeld/flask/feedredis.py
Fix wrong encoding of the indicators in JSON output. Now indicators are encoded via JSON library
=> Fixed #261

minemeld/ft/threatconnect.py
Now the pagination procedure do not fail if the response document do not include any data.
Fixed overriding by error main class "owner" attribute when the side config did not include it.
=> Fixed empty data return check

AUTHORS, minemeld/loader.py
This causes issues with the latest pip 18, where get_installed_distributions doesn't exist (even in _internal). It's clear pip doesn't intend for that function to be used. I've changed the call to use the suggestion on pip's issue [0], but I don't know enough about this part of Python to know if that has unintended side effects. Someone in-the-know should look at this before merging.
[0] pypa/pip#5243
=> Remove dep on get_installed_distributions

minemeld/flask/feedredis.py
In PAN-OS, a wildcard URL like `*.domain.com` from EDLs does not match a hostname without a leading component like `domain.com`. This PR implements and improvement on the `panosurl` modifier to duplicate URLs starting with a wildcard into 2 entries:
- before:
```
*.domain.com
```
- after: 
```
*.domain.com
domain.com
```
=> Adds support for duplicating wildcarded URLs

minemeld/ft/o365.py
Improves handling of O365 "indicators":
- attributes are now aggregated among multiple occurrences of the same indicator
- the list of attribute values are now stored in `o365_<attribute name>_list` attributes
- it's now easier to create filters based on specific attribute values
Example:
```
{
"confidence": 100,
"first_seen": 1565616931749,
"last_seen": 1565616931749,
"o365_category": "Allow",
"o365_category_list": [
"optimize",
"allow"
],
"o365_expressRoute": true,
"o365_expressRoute_list": [
"true"
],
"o365_id": 6,
"o365_id_list": [
"1",
"2",
"5",
"6"
],
"o365_notes": "Exchange Online POP3 migration",
"o365_notes_list": [
"exchange online imap4 migration",
"exchange online pop3 migration"
],
"o365_required": false,
"o365_required_list": [
"false",
"true"
],
"o365_serviceArea": …
```
=> Improvement to the O365 API Miner

minemeld/ft/cif.py, minemeld/ft/csv.py, requirements.txt
- Supersedes #350 (cifsdk pinned to 2.0.14) thanks @ckrez
- Fixes #346 (thanks @erush6861)
=> Updates cifsdk to 2.0.14, fixes arrow and fix oversight in CSV
